extends "res://tests/test_automatic_waiters.gd"

func run_tests() -> void:
	var r: Node = world()
	check(not r.set_menu_dishes([]), "Empty menu must be rejected")
	check(not r.set_menu_dishes([BURGER, BURGER]), "Duplicate dishes must be rejected")
	check(not r.set_menu_dishes([BURGER, PIZZA, NONE]), "More than two dishes must be rejected")
	check(r.set_menu_dishes([PIZZA]), "Single dish menu is valid")
	r.vip_spawn_chance = 0.0
	r.spawn_customer()
	for child in r.get_children():
		if child.has_method("get_customers"):
			for customer in child.get_customers():
				check(customer.requested_dish == PIZZA, "New customers must order from the selected menu")
	var group: Node = seat(r, "Table02Point", [BURGER], true)
	var vip: Node = group.get_customer(0)
	check(r.get_available_manual_dishes().has(BURGER), "Existing off-menu orders must remain cookable")
	for i in range(10):
		check(vip.prepare_next_dish(r.menu_dishes) == PIZZA, "VIP next rounds must use the current menu")
	check(not r.get_available_manual_dishes().has(BURGER), "Old dish must disappear once no outstanding customer needs it")
	check(DishTypes.menu_from_keys(["PIZZA"]) == [PIZZA], "Menu persistence must use stable keys")
	check(DishTypes.menu_from_keys(["REMOVED"]) == DishTypes.default_menu(), "Unknown old menu must recover a valid default")
	r.free()
	var editor: Node = load("res://scripts/ui/MenuEditor.gd").new()
	root.add_child(editor)
	editor.open_menu([BURGER, PIZZA])
	editor._toggle_dish(NONE)
	check(editor.selected == [BURGER, PIZZA], "A third selection must not exceed the cap")
	editor._toggle_dish(BURGER)
	check(not editor.dish_buttons[BURGER].disabled, "Freeing a slot enables other dishes")
	editor._toggle_dish(PIZZA)
	check(editor.apply_button.disabled, "An empty selection cannot be applied")
	editor._toggle_dish(BURGER)
	check(not editor.apply_button.disabled, "One selected dish can be applied")
	editor.open_menu([PIZZA])
	check(editor.selected == [PIZZA], "Reopening discards unapplied changes")
	editor.free()
	var game: Node = load("res://scenes/Main.tscn").instantiate()
	game.get_node("SaveManager").save_path = "res://tests/menu-unused-%s.json" % Time.get_ticks_usec()
	root.add_child(game)
	game.restaurant.unlocked_dishes = DishTypes.default_menu()
	game.restaurant.set_menu_dishes(DishTypes.default_menu())
	game.hud.get_node("KitchenPanel/VBoxContainer/MenuButton").pressed.emit()
	check(game.hud.menu_editor.visible, "Kitchen menu button must open the editor")
	game.hud.menu_editor._toggle_dish(BURGER)
	game.hud.menu_editor.apply_button.pressed.emit()
	check(game.restaurant.menu_dishes == [PIZZA], "Apply button must update the actual restaurant menu")
	game.free()
	print("MENU TESTS: ", "PASS" if failures == 0 else "FAIL", " (", failures, " failures)")
	quit(0 if failures == 0 else 1)
