extends "res://tests/test_automatic_waiters.gd"

func kitchen_click(r: Node) -> void:
	var event := InputEventMouseButton.new()
	event.button_index = MOUSE_BUTTON_LEFT
	event.pressed = true
	r._on_kitchen_point_input_event(root, event, 0)

func run_tests() -> void:
	var r: Node = world()
	var p: Node = r.player_waiter
	p.set_physics_process(false)
	plates(r, [BURGER, PIZZA, BURGER])
	kitchen_click(r)
	arrive(p)
	check(p.carried_dishes == [BURGER], "Default capacity must remain one")
	p.clear_carried_dishes()
	p.carry_capacity = 2
	kitchen_click(r)
	arrive(p)
	check(p.carried_dishes == [PIZZA, BURGER], "Automatic pickup must take the first two plates")
	check(not p.add_carried_dish(PIZZA), "Full hands cannot accept a third dish")
	p.clear_carried_dishes()
	plates(r, [PIZZA])
	kitchen_click(r)
	arrive(p)
	check(p.carried_dishes == [PIZZA], "One cooked plate must work with capacity two")
	plates(r, [BURGER, PIZZA])
	kitchen_click(r)
	arrive(p)
	check(p.carried_dishes == [PIZZA, BURGER] and r.get_ready_dishes() == [PIZZA], "Refill must respect the remaining slot")
	p.clear_carried_dishes()
	plates(r, [BURGER, PIZZA])
	var ids: Array[int] = r.get_ready_dish_ids()
	r.request_specific_ready_dish(ids[1])
	arrive(p)
	check(p.carried_dishes == [BURGER], "One manual selection must not automatically fill both slots")
	p.clear_carried_dishes()
	ids = r.get_ready_dish_ids()
	r.request_specific_ready_dish(ids[1])
	r.request_specific_ready_dish(ids[0])
	arrive(p)
	check(p.carried_dishes == [PIZZA, PIZZA], "Manual pickup must allow two distinct plates of the same type")
	p.clear_carried_dishes()
	plates(r, [BURGER, PIZZA, BURGER])
	ids = r.get_ready_dish_ids()
	r.request_specific_ready_dish(ids[2])
	r.request_specific_ready_dish(ids[0])
	r.request_specific_ready_dish(ids[1])
	check(r.selected_ready_dish_ids == [ids[2], ids[0]], "Third selection must not replace the selected plates")
	r.kitchen_point.take_ready_dish_by_id(ids[2])
	arrive(p)
	check(p.carried_dishes == [BURGER] and r.get_ready_dishes() == [PIZZA], "A stolen selection must not be substituted")
	p.clear_carried_dishes()
	ids = r.get_ready_dish_ids()
	r.request_specific_ready_dish(ids[0])
	r.request_specific_ready_dish(ids[0])
	check(not p.has_target and r.selected_ready_dish_ids.is_empty(), "Clicking again deselects and cancels an empty pickup")
	r.request_specific_ready_dish(ids[0])
	r.kitchen_point.take_ready_dish_by_id(ids[0])
	plates(r, [BURGER])
	r.get_selected_ready_dish_ids()
	arrive(p)
	check(p.carried_dishes.is_empty() and r.get_ready_dishes() == [BURGER], "Missing manual selections must never fall back to automatic pickup")
	var group: Node = seat(r, "Table02Point", [BURGER, BURGER])
	p.add_carried_dish(BURGER)
	p.add_carried_dish(PIZZA)
	r.selected_table = r.get_node("Table02Point")
	p.target_type = p.TargetType.TABLE
	r._on_player_waiter_destination_reached()
	check(p.carried_dishes == [PIZZA] and group.get_customer(0).has_received_food, "Deliver matching food and retain unmatched food")
	p.clear_carried_dishes()
	p.add_carried_dish(BURGER)
	p.add_carried_dish(BURGER)
	r._on_player_waiter_destination_reached()
	check(p.carried_dishes == [BURGER] and group.get_customer(1).has_received_food, "Do not deliver extra food once the table is eating")
	p.add_carried_dish(PIZZA)
	p.target_type = p.TargetType.TRASH
	r._on_player_waiter_destination_reached()
	check(p.carried_dishes.is_empty(), "Trash clears both dishes")
	r.free()
	r = world()
	p = r.player_waiter
	p.carry_capacity = 2
	group = seat(r, "Table02Point", [BURGER, PIZZA])
	p.add_carried_dish(BURGER)
	p.add_carried_dish(PIZZA)
	r.selected_table = r.get_node("Table02Point")
	p.target_type = p.TargetType.TABLE
	r._on_player_waiter_destination_reached()
	check(p.carried_dishes.is_empty() and group.get_customer(0).has_received_food and group.get_customer(1).has_received_food, "One table visit must deliver both requested dishes")
	r.free()
	var hud: Node = load("res://scenes/ui/HUD.tscn").instantiate()
	root.add_child(hud)
	var button_ids: Array[int] = [20, 21, 22]
	var selected_ids: Array[int] = [20, 22]
	hud.set_ready_dishes_buttons([BURGER, PIZZA, BURGER], button_ids)
	hud.set_ready_dish_selection(selected_ids, 2)
	var buttons: Array[Node] = hud.ready_dishes_container.get_children()
	check(buttons[0].button_pressed and buttons[2].button_pressed and buttons[1].disabled, "Panel must mark both chosen dishes and disable a third selection")
	selected_ids.clear()
	hud.set_ready_dish_selection(selected_ids, 1)
	check(not buttons[0].button_pressed and not buttons[1].disabled, "Panel must update selection even when cooked dishes do not change")
	hud.free()
	print("PLAYER CAPACITY TESTS: ", "PASS" if failures == 0 else "FAIL", " (", failures, " failures)")
	quit(0 if failures == 0 else 1)
