extends "res://tests/test_automatic_waiters.gd"

func run_tests() -> void:
	var r: Node = world()
	r.waiter_manager.apply_permanent_upgrades(true, true)
	check(r.waiter_manager.waiters.size() == 1 and r.waiter_manager.get_hired_count() == 0, "Permanent waiter must not count as hired")
	check(r.waiter_manager.can_hire(), "Permanent waiter must leave the paid hiring slot available")
	r.waiter_manager.apply_permanent_upgrades(true, true)
	check(r.waiter_manager.waiters.size() == 1, "Reapplying upgrades must not duplicate permanent staff")
	var a: Node = r.waiter_manager.waiters[0]
	a.set_physics_process(false)
	var group: Node = seat(r, "Table02Point", [BURGER, PIZZA])
	plates(r, [BURGER, PIZZA])
	begin_delivery(a)
	check(a.carried_dish == PIZZA and a.second_dish == BURGER, "Pick up the newest two dishes")
	check(r.get_ready_dishes().is_empty(), "Both reserved plates must leave the counter")
	arrive(a)
	check(a.carried_dish == BURGER and a.second_dish == NONE, "First delivery must retain the other plate")
	arrive(a)
	check(group.get_customer(0).has_received_food and group.get_customer(1).has_received_food, "Both distinct orders must be delivered")
	check(a.carried_dish == NONE, "Hands empty after both deliveries")
	r.free()

	r = world()
	r.waiter_manager.apply_permanent_upgrades(false, true)
	group = seat(r, "Table02Point", [BURGER, BURGER, BURGER])
	plates(r, [BURGER, BURGER, BURGER])
	a = waiter(r)
	var b: Node = waiter(r)
	a._physics_process(0.2)
	b._physics_process(0.2)
	check(r.waiter_manager.assignments[a]["dish_id"] != r.waiter_manager.assignments[b]["dish_id"], "Waiters must reserve distinct plates")
	check(r.waiter_manager.second_assignments[a]["customer"] != r.waiter_manager.assignments[a]["customer"], "Two identical dishes must reserve different customers")
	arrive(a)
	arrive(b)
	arrive(a)
	arrive(a)
	arrive(b)
	check(r.get_node("Table02Point").state == r.get_node("Table02Point").State.EATING, "Several waiters must serve a group without duplicate orders")
	r.free()

	r = world()
	r.waiter_manager.apply_permanent_upgrades(false, true)
	seat(r, "Table01Point", [PIZZA])
	seat(r, "Table02Point", [BURGER])
	plates(r, [BURGER, PIZZA])
	a = waiter(r)
	a._physics_process(0.2)
	r.kitchen_point.take_ready_dish_by_id(1)
	arrive(a)
	check(a.carried_dish == BURGER and a.second_dish == NONE, "Stolen first plate must not lose the second reservation")
	arrive(a)
	check(r.get_node("Table02Point").state == r.get_node("Table02Point").State.EATING, "Remaining plate still reaches its customer")
	r.free()

	r = world()
	r.waiter_manager.apply_permanent_upgrades(false, true)
	seat(r, "Table01Point", [PIZZA])
	seat(r, "Table02Point", [BURGER])
	plates(r, [BURGER, PIZZA])
	a = waiter(r)
	begin_delivery(a)
	r.get_node("Table01Point").receive_food(PIZZA)
	a._physics_process(0.2)
	check(a.carried_dish == BURGER and a.state == a.State.TO_TABLE, "Serve useful second dish before trashing obsolete first dish")
	arrive(a)
	check(a.carried_dish == PIZZA and a.state == a.State.TO_TRASH, "Only the obsolete dish must go to trash")
	arrive(a)
	check(a.carried_dish == NONE and a.second_dish == NONE, "Trash must finish remaining dish")
	r.free()
	print("WAITER CAPACITY TESTS: ", "PASS" if failures == 0 else "FAIL", " (", failures, " failures)")
	quit(0 if failures == 0 else 1)
