extends RefCounted

# EDITA SOLO LOS NÚMEROS. 20 significa 20 %, no 0.20.
# Los negativos reducen la estadística. Reinicia el juego tras guardar.
# La lógica y los textos leen estos mismos valores. Ver docs/AJUSTAR_ETIQUETAS.md.
const PERCENTAGES := {
	# Para compartir: pedidos iguales de una misma mesa / personas del grupo.
	"compartir_cocina_2": 20.0,
	"compartir_cocina_3": 30.0,
	"compartir_cocina_4": 40.0,
	"compartir_repeticion_2": 20.0,
	"compartir_repeticion_3": 33.0,
	"compartir_repeticion_4": 50.0,
	"cruda_cocina_por_plato": 5.0,
	"picante_camareros_por_plato": 2.0,
	"picante_paciencia_por_plato": -2.0,
	"fria_cocina": 30.0,
	"sushi_comer": 25.0,
	"sushi_clientes": 20.0,
	"caldo_paciencia_2": 50.0,
	"caldo_tiempo_cocina_2": 10.0,
	"caldo_paciencia_4": 75.0,
	"caldo_tiempo_cocina_4": 20.0,
	"frita_clientes": 50.0,
	"frita_vip": -30.0,
	"desayuno_valor": 15.0,
	"rapida_cocina": 30.0,
	"gourmet_vip": 50.0,
	"gourmet_clientes": -50.0,
	"vegetariana_paciencia_cola": 15.0,
	"vegetariana_paciencia_mesa": 15.0,
	"vegetariana_clientes_con_carne": -15.0,
	"vegana_valor_vegetales_1": 5.0,
	"vegana_valor_vegetales_5": 15.0,
	"vegana_valor_vegetales_10": 30.0,
	"vegana_valor_vegetariana_10": 10.0,
	"vegana_clientes_10": -15.0,
	# Nacionalidades: valor por cada plato de ese origen en la carta.
	"japonesa_valor_cruda": 2.0,
	"italiana_valor_pasta": 2.0,
	"mexicana_valor_picante": 2.0,
	"china_valor_arroz": 2.0,
	"espanola_valor_compartir": 2.0,
	"peruana_valor_pescado": 2.0,
	"estadounidense_valor_rapida": 2.0,
	"francesa_valor_gourmet": 2.0,
	"marisco_valor_6": 25.0,
	"marisco_vip_6": 5.0,
	"arroz_cocina_2": 10.0,
	"arroz_cocina_5": 30.0,
	"carne_valor_5": 30.0,
	"carne_cocina_5": -30.0,
	"pescado_comer_3": 15.0,
	"pescado_comer_6": 30.0,
	"pescado_marisco_valor": 10.0,
	"patata_camareros_2": 5.0,
	"patata_camareros_5": 10.0,
	"patata_camareros_10": 25.0,
	"vegetales_cola_1": 2.0,
	"vegetales_cola_3": 8.0,
	"vegetales_cola_6": 15.0,
	"vegetales_cola_9": 40.0,
	"vegetales_cocina_vegana_9": 25.0,
	"pasta_clientes_1": 2.0,
	"pasta_clientes_4": 10.0,
	"pasta_clientes_7": 25.0,
	"pasta_valor_con_caldo": 15.0,
	"masa_valor_2": 15.0,
	"masa_valor_6": 25.0,
	"masa_valor_10": 50.0,
	"masa_cocina_10": 25.0
}
